services:
  opencr-setup:
    build:
      context: docker/opencr_setup
    volumes:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - OPENCR_PORT=/dev/ttyACM0
      - OPENCR_MODEL=burger
    privileged: true
  ros:
    build:
      context: docker/ros
    volumes:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
      - ./ws/:/home/ubuntu/ws
    working_dir: /home/ubuntu/ws
    privileged: true
    environment:
      - ROS_DOMAIN_ID=30 
      - LDS_MODEL=LDS-02
      - TURTLEBOT3_MODEL=burger
    user: ubuntu
